language: node_js
node_js:
  - 'node'
# Currently required as version of yarn is too old
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - 'yarn clear-test-cache'
  - 'yarn cache clean'
before_deploy:
  - yarn build
notifications:
  email:
    - xwatkins@ebi.ac.uk
    - mmahmoudy@ebi.ac.uk
    - dlrice@ebi.ac.uk
  slack: ebi-uniprot:7OMFmmkUp9uxH3SXgyq7OVb3
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
